products/urls.py
from django.urls import path
from . import views



app_name = 'products'

urlpatterns=[
    path('', views.index, name='index'),
    path('index', views.indexx, name='indexx'),
    path('login', views.login_user, name='login'),
   
    path('client', views.client, name='client'),
    path('logout', views.logout_user, name='logout'),
    path('login_client', views.login_client, name='login_client'),
    path('cart_page', views.cart_page, name='cart_page'),

    path('plus_item/<int:variation_id>', views.plus_item, name='plus_item'),
    path('new_add', views.new_add, name='new_add'),
    path('view/<int:product_id>/product_item', views.view_product, name='view')
   
] 

shopping/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    fullname = models.CharField(max_length=50)
    email =  models.EmailField(max_length=50, unique=True)
    image =  models.ImageField(null=True, blank=True, upload_to='image')
    password = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.fullname



class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    image = models.ImageField(null=True,upload_to='image')
    

    def __str__(self):
        return self.name


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,default=1)
    name = models.CharField(max_length=255, null=True, unique=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='image')

    def __str__(self):
        return self.name+"("+self.product.name+")"


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE,default=1 )
    cart_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    completed = models.BooleanField(default=False)
    

    @property
    def get_cart_total(self):
        cartitems= self.cartitem_set.all() 
        total = sum([item.get_total for item in cartitems])
           
        return total

    @property
    def qty_cart_total(self):
        cartitems= self.cartitem_set.all() 
        total = sum([item.quantity for item in cartitems])
           
        return total    



    def __str__(self):
        return self.user.username +"("+ str(self.id)+")"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE )
    variation = models.ForeignKey(Variation, on_delete = models.CASCADE, default=1 )
    quantity = models.IntegerField(default=0)

    @property
    def get_total(self):
        total = self.variation.price * self.quantity
        return total


    def __str__(self):
        return self.variation.name +"("+ str(self.id)  +")"

products/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from .models import Client


class RegisterUserForm(UserCreationForm):
    
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control','placeholder':'Email'}))
    # first_name =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Firstname'}),min_length=3,max_length=15)
    # last_name =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Lastname'}), min_length=3,max_length=15)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control','placeholder':'Username'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control','placeholder':'************'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control','placeholder':'************'})

    class Meta:
        model = User
        fields = ('username','email','password1', 'password2')
    

class ClientForm(ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Fullname'}),min_length=3,max_length=50)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control','placeholder':'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder':'************'}))
    image =  forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control','placeholder':'Image'}))

    
    class Meta:
        model = Client
        fields = ('fullname', 'email', 'password')

products/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Product, Client, Cart, CartItem, Variation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterUserForm , ClientForm  


def index(request):

    products = Product.objects.all()

    return render(request, 'index.html', {'products':products})


def view_product(request, product_id):
    products = Product.objects.all()
    user = request.user
    cart, created = Cart.objects.get_or_create(user = user, completed = False)
    product = Product.objects.get(id = product_id)
    product_details = Variation.objects.filter(product = product) 
    

    return render(request, 'view_product.html', {'cart':cart,'product':product,'product_details':product_details})


def indexx(request):
    products = Product.objects.all()

    return render(request, 'index.html', {'products':products})


def client(request):
    products = Product.objects.all()
    user = request.user
    cart, created = Cart.objects.get_or_create(user = user, completed = False)
    return render(request, 'user.html', {'products':products, 'cart':cart})


def logout_user(request):
    logout(request)
    messages.success(request, ("Succesfully Logout"))

    return redirect('products:index')


def login_client(request):
    if request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, ("Succesfully LoggedIn"))
            return redirect('products:client')
            
        else:
            messages.error(request, ("Incorrect Credential"))
            return redirect('products:login')
            
    else:
        return render(request, 'login.html')


def login_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password =  form.cleaned_data['password1']
            user = authenticate(username = username, password = password)
            login(request, user)
            messages.success(request, ("Succesfully Registered"))
            return redirect('products:client')
    else:

        form = RegisterUserForm()
    return render(request, 'login.html', {'form':form}) 


def cart_page(request):
    if request.user.is_authenticated:
        user = request.user
        cart, created = Cart.objects.get_or_create(user = user, completed = False)
        cartitems = cart.cartitem_set.all()   
    else:
        cart = {'get_cart_total':0, 'qty_cart_total':0}
        cartitems = [] 
    return render(request, 'cart.html', {'cartitems':cartitems,'cart':cart})




def new_add(request):

    if request.method == "POST":
        product_id = request.POST['product_id']
        variation_id = request.POST['variation_id']
        user = request.user
        product = Product.objects.get(id=product_id)
        variation_id = Variation.objects.get(id=variation_id, product=product_id)
        cart, created = Cart.objects.get_or_create(user = user, completed = False)
        cartitem, created = CartItem.objects.get_or_create(cart = cart, variation = variation_id)

        cartitem.quantity += 1
        cartitem.save()
    
    return redirect('products:client')


def plus_item(request, variation_id):
    user = request.user
    variation = Variation.objects.get(id = variation_id)
    cart= Cart.objects.get(user = user, completed = False)
    cartitem = CartItem.objects.get(cart = cart, variation = variation)

    if request.method == "POST":
        if "plus-btn" in request.POST:
            cartitem.quantity += 1
            cartitem.save()
        else:
            cartitem.quantity -= 1
            cartitem.save()
            if cartitem.quantity == 0:
                cartitem.delete()
        
    return redirect('products:cart_page')


            

        

products/templates/cart.html
{% extends 'header_user.html' %}
{% block content %}
<div class="container">
	<div class="row">
		<h3 class="text-center">Your Products in the Cart</h3>
	</div>
	<div class="row mt-2">
     <div class="col-md-7">
     	<h3>My Cart</h3>
     	<hr>
		
     	{% for item in cartitems  %}
		
		
		 <div class="card mb-3 show" >
		  <div class="row g-0">
		    <div class="col-md-4">
				<!-- product is field in CartItem class -->
		      <img
		        src="{{ item.variation.image.url }}"
		        alt="..."
		        class="img-fluid rounded-start"
		        style="width:200px ;height: 120px"
		      />
		    </div>
		    <div class="col-md-8">
		    	<div class="row">
		    		
		    	<div class="col-md-5">
		      <div class="">
		        <h5 class="card-title">{{ item.variation.name }}</h5>
		        Product: <i>{{ item.variation.product.name }}</i><br>
		        
				{{ item.variation.price }} frw/item<br>
		        
		        <strong class="text-dark font-italic">{{ item.get_total }} frw</strong><br>
		        <!-- <form action="" method="post">
		        <button type="submit" class="btn btn-danger" name="remove">Remove</button>
		        </form> -->
				
		      </div>
		      </div>
		      <div class="col-md-7 mt-5">
		      	<form action="{% url 'products:plus_item' item.variation.id %}" method="post">
				{% csrf_token %}

		      	<button type="submit" name="minus-btn"class="  btn bg-light border rounded-circle d-inline">-</button>
		      	<input type="text" value="{{ item.quantity}}" id="quantity" name="quantity" class="form-control w-25 d-inline">
		      	<button type="submit" name="plus-btn"class=" btn bg-light border rounded-circle d-inline">+</button>
		      	</form>
		      </div>
		      </div>
		    </div>
		  </div>
		</div>
		{% endfor %}      

     	
     	  
     </div>
     <div class="col-md-4 offset-md-1 border rounded mt-5 bg-white h-25">
     	<h3>Price Details</h3>
     	<hr>
		<div class="row">
     	 <div class="col-md-6">
     	 	
            <h6>Price all of ({{ cart.qty_cart_total }} Items)</h6>
            <h6>Delivery Charges</h6>
            <hr>
            <h6>Amount Payable</h6>
     	 </div>
     	 <div class="col-md-6">
     	 	<h6><strong id="">{{ cart.get_cart_total }}</strong></h6>
			<h6><strong id="">0</strong></h6></h6>
			<hr>
			<h6><strong id="price">{{ cart.get_cart_total }}</strong> frw</h6></h6>
     	 	
     	 </div>
		</div>
     </div>
	</div>
</div>


{% endblock %}

products/templates/edit_user.html
<?php
include 'session.php';

include 'header_user.php';

?>
<div class="container">
	<div class="row">
		<h3 class="text-center">Your Purchase's Details</h3>
	</div>
	<div class="row mt-2">

	  <div class="col-md-8 offset-md-2">
       <?php
      if (isset($_POST["register"])){
          $email = $_POST["email"];
          $name=$_POST["name"];
          $password=$_POST["password"];
          
          
        $add="UPDATE customer SET fullname='$name',email='$email',password='$password'";

      
        $query=mysqli_query($db,$add);
            if ($query) {
              ?> 
                <div class="alert alert-success strover animated bounce col-md-12" id="sams1">
                  <button class="close" data-dismiss="alert"></button>
                  <center><i>Successfuly Updated</i></center>
                </div>
              <?php
            }

      }
    
      $shae= "SELECT * FROM customer WHERE cus_id='$cust_id' ";
  $dool= mysqli_query($db,$shae);
  $row= mysqli_fetch_array($dool);

      ?>
    <form method="post" action="#" id="reg_form"enctype="multipart/form-data">
              
              
              <div class="row">
                <div class="form-group col-md-12">
                    <label for="name">Fullname</label>
                    <!-- <div class="input-group"> -->
                    <!-- <span class="input-group-addon"><i class="fa fa-user"></i></span> -->
                    <input type="text" class="form-control" id="name" name="name" placeholder=" Fullname" value="<?php echo $row['fullname'];?>" required >
                    
                  <!-- </div> -->
                </div>
              </div>
              <div class="row">

                <div class="form-group col-md-12">
                  <label for="inputAddress" >Email</label>
                  <!-- <div class="input-group"> -->
                  <!-- <span class="input-group-addon"><i class="fa fa-lock"></i></span> -->
                  <input type="text" class="form-control" id="email" name="email"  value="<?php echo $row['email'];?>" required>
                <!-- </div> -->
              </div>
                
              </div>
              <div class="row">
              
              
              
                 <div class="form-group col-md-12">
                    <label for="email" >Password</label>
                    <!-- <div class="input-group"> -->
                    <!-- <span class="input-group-addon"><i class="fa fa-envelope"></i></span> -->
                    <input type="text" class="form-control" id="email" name="password"  value="<?php echo $row['password'];?>" required>
                <!--   </div> -->
                </div>
              </div> 
              <div class="row mt-2">
              <div class="form-group col-md-12">
              <button type="submit" name="register" id="register" class="btn btn-outline-dark btn-block"><i class="fa fa-paper-plane"></i> Update</button>
            </div>
            </div>
            </form>
  </div>
	</div>
</div>
<!-- <table class="table table-bordered border-primary"></table> -->
<?php
include 'footer_user.php';
?>

products/templates/header_user.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>JJ Supermarket</title>
    
    <!-- MDB icon -->
    
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
  />
  <!-- Google Fonts -->
  
  <link rel="icon" href="{% static 'products/img/apple.png' %}" type="image/x-icon" />
    
   <link rel="stylesheet" href="{% static 'products/font-awesome-4.7.0/css/font-awesome.min.css' %}">
   <link rel="stylesheet" href="{% static 'products/css/validecss.css' %}">
   <link rel="stylesheet" href="{% static 'products/css/style.css' %}">
   
    <link rel="stylesheet" href="{% static 'products/css/mdb.min.css' %}" />
   
    
  </head>
 
  <body>
    <!-- Start your project here-->
    <header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fa fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar brand -->
          
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products:client' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'products:client' %}">Homepage</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
          </ul>
          <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
          <!-- Icon -->
         
            <span><i class="fa fa-shopping-cart text-light"></i></span>
            <a href="{% url 'products:cart_page' %}" class="badge badge-pill bg-danger">{{ cart.qty_cart_total }}</a>
            
          <!-- Notifications -->
          |||||||
          <a
            class="text-reset me-3 dropdown-toggle hidden-arrow "
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
           <i class="text-light">{{ user.username }}</i>
            <i class="fa fa-angle-double-down text-light"></i>
            
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink"
          >
            
            <li>
              <a class="dropdown-item" href="{% url 'products:logout' %}">Logout</a>
            </li>
          </ul>

          <!-- Avatar -->
          <a
            class="dropdown-toggle d-flex align-items-center hidden-arrow"
            href="#"
            
          >
            <img
              src="{% static 'img/username.png' %}"
              class="rounded-circle"
              height="25"
              alt=""
              loading="lazy"
            />
          </a>
        
        </div>
        <!-- Right elements -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    </header>
{% block content %}

{% endblock %}

{% include 'footer_user.html' %}


<!-- Custom scripts -->
<!-- <script type="text/javascript" src="{% static 'products/js/cart.js' %}"></script> -->
<!-- <script type="text/javascript" src="{% static 'js/cart.js' %}"></script> -->
</body>
</html>

products/templates/login.html
{% extends 'header.html' %}

{% block content %}
    <main class="mt-5">
      <div class="container">
        <section class="text-center mb-4">
        <div class="card mb-3 offset-2" style="max-width: 840px;">
          <div class="row g-0">
            <div class="col-md-6 p-3 ">
              <h3>Signup Form</h3>
              
              {% if form.errors %}
                
                  <div class="alert alert-danger strover animated shake col-md-12"id="sams1">
                    
                    <center><i>{{ form.errors }}</i></center>
                 </div>
                
              {% endif %}
                       
              <form method="POST" action="{% url 'products:login' %}" id="reg_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group col-md-12 mb-3">
                  <div class="input-group ">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    {{form.username}}
                      <span class="input-group-text" id="basic-addon2">Username</span>
                  </div>
                  </div>
                  
                  <div class="form-group col-md-12 mb-3">
                  <div class="input-group " id="email">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    {{form.email}}
                      <span class="input-group-text" id="basic-addon2">Email</span>
                  </div>
                  </div>
                  <!-- <div class="form-group col-md-12 mb-3">
                    <div class="input-group " id="email">
                      <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                      {{form.image}}
                        <span class="input-group-text" id="basic-addon2">Image</span>
                    </div>
                    </div> -->
                  <div class="form-group col-md-12 mb-3">
                  <div class="input-group " id="password">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
                    {{form.password1}}
                      <span class="input-group-text" id="basic-addon2">Password</span>
                  </div>
                  </div>
                  <div class="form-group col-md-12 mb-3">
                    <div class="input-group ">
                      <span class="input-group-text" id="basic-addon1"><i class="fa fa-lock"></i></span>
                      {{form.password2}}
                        <span class="input-group-text" id="basic-addon2">Confirm Password</span>
                    </div>
                    </div>
                  <div class="form-group col-md-12 mb-3">
                  <div class="input-group ">
                    <button type="submit" class="btn btn-primary btn-block" name="register">Signup</button>
                  </div>
                  </div>
                  
             </form>
             
             

             
            </div>
            <div class="col-md-6 p-3 ">
              <h3>Signin Form</h3>
             
              {% if messages %}
               {% for message in messages %} 
              <div class="alert alert-danger strover animated shake col-md-12"id="sams1">
                
                <center><i>{{ message }}</i></center>
             </div>
               {% endfor %}
             {% endif %}
              <form method="post" action="{% url 'products:login_client' %}" >
                {% csrf_token %}
              <label for="basic-url" class="form-label">Your Username</label>
              <div class="input-group mb-3">
               <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
               <input type="text" class="form-control" placeholder="Username" aria-label="Username"
                 aria-describedby="basic-addon1" name="username" />
                 <span class="input-group-text" id="basic-addon2">Username</span>
             </div>
             <label for="basic-url" class="form-label">Your Password</label>
             <div class="input-group mb-3">
               <span class="input-group-text" id="basic-addon1"><i class="fa fa-key"></i></span>
               <input type="password" class="form-control" placeholder="*************" aria-label="Username"
                 aria-describedby="basic-addon1" name="password" />
                 <span class="input-group-text" id="basic-addon2">Password</span>
             </div>
             
             <div class="input-group mb-3">
               <button type="submit" class="btn btn-primary btn-block" name="login">Send</button>
             </div>
             </form>
             
            </div>
          </div>
        </div>
        </section>
      </div>
    </main>

{% endblock %}

products/templates/logout.html
<?php
session_start();
if(isset($_SESSION['admin_id']))
{
session_destroy();
}
header("location:index.php");
?>

products/templates/session.html
<?php
session_start();
include 'conn.php';
if (!isset($_SESSION['cust_id'])) {
	header("location:index.php");
}

$cust_id=$_SESSION['cust_id'];

$userr= "SELECT * FROM customer WHERE cus_id='$cust_id'";
$exl= mysqli_query($db,$userr);
$erow= mysqli_fetch_array($exl);
$admin_name=$erow['fullname'];
$admin_email=$erow['email'];
$admin_password=$erow['password'];


// 0787559716
// 0783150141

  ?>

products/templates/user.html
{% extends 'header_user.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<h3 class="text-center">List of Product</h3>
	</div>
	<div class="row mt-2">
		<section class="text-center mb-4">
		  <div class="row mt-2">
		    
			{% if messages %}
			{% for message in messages %}
			  
			  <div class="alert alert-success strover animated bounce col-md-12"id="sams1">
				
				<center><i>{{ message }}</i></center>
			 </div>
			{% endfor%}
		  {% endif %}
		  {% for product in products %}
		  <div class="col-md-4 mb-4">
		  <div class="card">
		  <div class=" hover-overlay ripple" data-mdb-ripple-color="light">

			<img
			  src="{{ product.image.url }}"
			  class="img-fluid"
			  style="width:180px;height: 120px;"
			/>
			
		  </div>
		  <div class="card-body">
			<h5 class="card-title"></h5>
			<p class="card-text font-italic">
			  {{ product.name }} <br>
			 
			</p>
			<a href="{% url 'products:view' product.id %}" id="" class="btn btn-primary" >View</a>

		  </div>
		</div>
		</div>
  {% endfor %}  
		      
		    
		 
		  </div>
		</section>
	</div>
</div>

{% endblock %}

products/templates/view_product.html
{% extends 'header_user.html' %}

{% block content %}

<div class="container">
	
	<div class="row mt-2">
        
		<section class="text-center mb-4">
            <div class="col-md-7 offset-2" >
                <div class="card mb-3">
                    <div class="card-img-top" alt="Wild Landscape" >
                        <div id="carouselExampleControls" class="carousel slide" data-mdb-ride="carousel">
                            <div class="carousel-inner">
                              
                              <div class="carousel-item active">
                                <img src="{{ product.image.url }}" style="height: 300px;" class="d-block w-100" alt="Wild Landscape" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>Product Image</h5>
                                    <p>Undercover Product Image.</p>
                                  </div>
                              </div>
                              
                              {% for item in product_details %}
                              <div class="carousel-item">
                                <img src="{{ item.image.url}}" style="height: 300px;" class="d-block w-100" alt="Wild Landscape"/>
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ item.name }}</h5>
                                    <p>{{ item.price }} Rwf</p>
                                  </div>
                              </div>
                              {% endfor %}
                              
                            </div>
                            <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleControls" data-mdb-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleControls" data-mdb-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Next</span>
                            </button>
                          </div>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title">{{ product.name }}</h5>
                      <p class="card-text">
                  
                      </p>
                      <form method="post" action="{% url 'products:new_add'%}" >
                        {% csrf_token %}
                      
                     <div class="row">
                        {% for items in product_details  %}
                        <div class="col-md-4">
                            {{ items.name }}:<input type="radio" name="variation_id" value="{{ items.id }}" class="form-radio">

                        </div>
                        {% endfor %}
                    </div>
                     <input type="hidden" name="product_id" value="{{ product.id }}" >
                     
                     <div class="input-group mb-3">
                       <button type="submit" class="btn btn-primary btn-block" name="login">Add to cart</button>
                     </div>
                     </form>
                      <p class="card-text">
                        <small class="text-muted"><i>Choose Your Desired Item </i> </small>
                      </p>
                    </div>
                  </div>
                
            
            </div>
		</section>
	</div>
</div>

{% endblock %}